package org.nalby.yobatis.book.model.base;

/*
 * This class corresponds to the table 'book', and is generated by MyBatis Generator.
 * Do NOT modify as it will be overwrote every time MyBatis Generator runs, put your code into
 * Book instead.
 */
public abstract class BaseBook {
    protected Long id;

    protected String name;

    protected Long author;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Long getAuthor() {
        return author;
    }

    public void setAuthor(Long author) {
        this.author = author;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append("[");
        sb.append("id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", author=").append(author);
        sb.append("]");
        return sb.toString();
    }

    /**
     * Copy properties of this object to {@code dest} object.
     * @param dest the object to copy properties to.
     * @return the dest object.
     */
    public BaseBook copy(BaseBook dest) {
        if (dest == null) {
            throw new NullPointerException("dest must not be null.");
        }
        dest.id = this.id;
        dest.name = this.name;
        dest.author = this.author;
        return dest;
    }
}